"""empty message

Revision ID: 4339532007b4
Revises: d86b70a2a14d
Create Date: 2017-04-30 12:34:48.571338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4339532007b4'
down_revision = 'd86b70a2a14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotted_bird', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotted_bird', 'image')
    # ### end Alembic commands ###
